apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-plant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-plant
  template:
    metadata:
      labels:
        app: shop-plant
    spec:
      containers:
        - name: shop-plant
          image: md290801/shop-plant:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: shop-plant-service
spec:
  selector:
    app: shop-plant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP